apps/index/urls.py
from django.urls import path
from . import views
app_name = 'index'

urlpatterns =[
    path('user/register/', views.SignUpView.as_view(), name='register_user'),
    path('', views.Index.as_view(), name="index")
    
    
]

words/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("apps.index.urls")),
]

apps/index/models.py
from typing import Iterable, Optional
from django.db import models
from django.contrib.auth.models import AbstractUser
# Create your models here.
class CustomUser(AbstractUser):
    score = models.IntegerField(null=True, blank=True)

    def __str__(self) -> str:
        return self.score
    

class SongsWord(models.Model):
    url_youtube = models.URLField(null=True, blank= True)
    name = models.CharField(max_length=150, null=True, blank=True)
    
    def __str__(self) -> str:
        return self.name
    
    def save(self):
        self.url_youtube = self.url_youtube.replace("watch?v=", "embed/")
        return super().save() 
    
class Word(models.Model):
    id_songs = models.ForeignKey(SongsWord,on_delete=models.CASCADE, null=True, blank=True)
    word = models.CharField(max_length=150)
    WORD_CHOICES = (
        ('G','Grave'),
        ('A','Aguda')
    )
    type_word = models.CharField(choices=WORD_CHOICES, max_length=1)
    order_b = models.IntegerField(null=True,blank=True)
    def __str__(self) :
        return self.word

apps/index/forms.py
from django import forms
from .models import *
from django.contrib.auth.forms import UserCreationForm

class CustomUserCreationForm(UserCreationForm):
    class Meta:
        model = CustomUser
        fields = ('username', 'password1', 'password2')

apps/index/views.py
from typing import Any, Dict
from django.forms.models import BaseModelForm
from django.http import HttpResponse
from django.contrib.auth import login
from django.shortcuts import render
from django.urls import reverse_lazy
from django.views.generic import TemplateView, CreateView
from .forms import CustomUserCreationForm
from . models import *

class SignUpView(CreateView):
    form_class = CustomUserCreationForm
    success_url = reverse_lazy('index')
    template_name = 'registration/signup.html'
    
    def form_valid(self, form):
        response = super().form_valid(form)
        login(self.request,self.object)
        return response
    
class Index(TemplateView):
    template_name = "index/home.html"
    
    def get_context_data(self, **kwargs: Any) -> Dict[str, Any]:
        context = super().get_context_data(**kwargs)
        questions = Word.objects.all().order_by('?')[:10]
        context['questions'] = questions
        music_questions = SongsWord.objects.all().order_by('?').first()
        context['music_questions'] = music_questions
        return context

# Create your views here.

apps/index/templates/index/home.html
{% extends 'index/base.html' %}
{% load static %}
{% block content %}

  <div class="container">
    <div class="wrapper">
      <div class="screen-section main-screen">
        <div class="quiz-image-wrapper">
          <img class="quiz-image" src="https://yt3.ggpht.com/a/AATXAJzm4JsH-ufa05iHinmQoCYqc2MwYL--addt=s900-c-k-c0xffffffff-no-rj-mo" alt="LOGO Tecnico central" />
        </div>
        <h1>Trivia de palabras graves y agudas </h1>
        <div class="button-container">
          <div class="button-outer">
            <button class="default-button" id="start">Inicio</button>
          </div>
          <div class="button-outer">
            <button class="default-button" id="how-to">¿Como jugar?</button>
          </div>
        </div>
        <div class="quiz-logo">
          <img src="" alt="" />
        </div>
      </div>

      <div class="screen-section how-to-play-screen hidden">
        <img class="quiz-corner-logo" src="https://static-00.iconduck.com/assets.00/kaitai-icon-256x256-sdz2ra2u.png" alt="DanielChikara" />
        <button type="button" id="close-how-to" class="close-button">X</button>
        <h2 class="title">Jugar es fácil y divertido</h2>
        <p class="text"></p>

        <p class="text">Diferencia las palabras graves de las agudas</p>

        <p class="text">Tienes que diferenciar las palabras graves de las agudas seleccionando a cuál pertenece la palabra</p>

        <p class="text">Palabras agudas también llamadas oxítonas. Su sílaba tónica es la última y se escriben con tilde cuando terminan en vocal (mamá), -n (canción) o -s (jamás).

          No se escribe sin tilde en en el resto de las terminaciones (animal, señor, pared, cantar...). Tampoco lleva tilde Si la -s va detrás de otra consonante (debuts, robots, entrecots).</p>

        <p class="text">palabras graves también llamadas llanas o paroxítonas y son el grupo más numeroso en el idioma español. Su sílaba tónica es la penúltima y se escriben con tilde cuando no terminan en vocal, -n o -s ( lápiz, césped, cárcel...).</p>
        <button class="default-button" id="start2">Vamos a jugar</button>
        <div class="quiz-logo">
          <img src="" alt="" />
        </div>
      </div>

      <div class="screen-section quiz-screen hidden">
        <div class="quiz-screen-step">
          preguntas <span id="question-index"></span> de <span id="question-count"></span>
        </div>
        <div class="quiz-image-wrapper">
          <img class="quiz-image" id="question-image" src="" alt="" />
        </div>
        <div class="quiz-timer" id="progress-bar"></div>
        <div class="quiz-question" id="quiz-text"></div>
        <div class="button-container" id="answers-container">
          <div class="button-outer">
            <button id="answer0" class="default-button"></button>
          </div>
          <div class="button-outer">
            <button id="answer1" class="default-button"></button>
          </div>
        </div>
        <div class="quiz-logo">
          <img src="https://th.bing.com/th/id/R.7f46e32d85d84ee6557d11dbaebed9a4?rik=UIOnnrFEZNAQrQ&riu=http%3a%2f%2fwww.acofi.edu.co%2fwp-content%2fuploads%2f2020%2f02%2fESCUELA-TECNOLOGICA-INSTITUTO-TECNICO-CENTRAL-150x150.jpg&ehk=Azhqg8SIcHyXMtoKWytJrH3QHI1uRq64Kb%2bcKFTfgBc%3d&risl=&pid=ImgRaw&r=0" alt="Logo tecnico central" />
        </div>
      </div>

      <div class="screen-section result-screen hidden">
        <div class="quiz-image-wrapper">
          <img class="quiz-image" src="https://yt3.ggpht.com/a/AATXAJzm4JsH-ufa05iHinmQoCYqc2MwYL--addt=s900-c-k-c0xffffffff-no-rj-mo" alt="UCentral" />
        </div>
        <p class="score">
          <span id="score"></span> de <span id="score-total"></span>
        </p>
        <h1 id="score-name" class="score-name"> Trivia de palabras agudas y graves</h1>
        <span class="description">Juego desarrollado para la clase de comunicación escrita desarrollado por Brandon Ortega y Diego Reyes</span>

        <!-- <button>share facebook</button> -->
        <!-- <button>share twitter</button> -->
        <button class="default-button" id="start3">Volver a jugar</button>

        <div class="quiz-logo">
          <img src="" alt="" />
        </div>
      </div>
    </div>
  </div>
  <script>
    
    


    (function() {
      let startButton = document.querySelector('#start');
      let startButton2 = document.querySelector('#start2');
      let startButton3 = document.querySelector('#start3');
      let howToButton = document.querySelector('#how-to');
      let closeHowToButton = document.querySelector('#close-how-to');
      let howToPlayScreen = document.querySelector('.how-to-play-screen');
      let mainScreen = document.querySelector('.main-screen');
      let quizScreen = document.querySelector('.quiz-screen');
      let resultScreen = document.querySelector('.result-screen');
    
      startButton.addEventListener('click', showGamePlay);
      startButton2.addEventListener('click', showGamePlay);
      startButton3.addEventListener('click', showGamePlay);
    
      howToButton.addEventListener('click', function() {
        howToPlayScreen.classList.remove('hidden');
        mainScreen.classList.add('hidden');
      });
    
      closeHowToButton.addEventListener('click', function() {
        howToPlayScreen.classList.add('hidden');
        mainScreen.classList.remove('hidden');
      });
    
      let questionLength = 10;
      let questionIndex = 0;
      let score = 0;
      let questions = [];
      let timer = null
    
      function showGamePlay () {
        // TODO: show spinner
        questionIndex = 0;
        questions = [];
        score = 0;
    
        window.setTimeout(function () {
          // TODO: get questions from server
    
          mainScreen.classList.add('hidden');
          howToPlayScreen.classList.add('hidden');
          resultScreen.classList.add('hidden');
          quizScreen.classList.remove('hidden');
          
          {% for a in questions %}
     questions.push( { word: " {{a.word}} ", answers: ['Aguda', 'Grave'], correct: '{{a.get_type_word_display}}'},)
    {% endfor %}
    console.log(questions)
          
          let questionCount = document.getElementById('question-count');
          questionCount.innerHTML = questionLength.toString();
          populate()
        }, 50);
      }
    
      let isEnded = function () {
        return questionLength === questionIndex;
      };
    
      function populate() {
        let answersContainer = document.getElementById('answers-container');
        let answerButtons = answersContainer.querySelectorAll('.default-button');
    
        answerButtons.forEach(function(element) {
          element.disabled = false;
          element.classList.remove('correct');
          element.classList.remove('wrong');
        });
    
        if (isEnded()) {
          showScores();
        } else {
          startProgressbar();
          timer = window.setTimeout(function() {
            guess(null);
          }, 10000);
    
          setQuizText('que tipo de palabra es:  '+ questions[questionIndex].word);
    
          let imageElement = document.getElementById('question-image');
          //imageElement.src = './assets/wapuus/' + questions[questionIndex].image + '.png';
    
          // show choices
          let choices = questions[questionIndex].answers;
          for (let i = 0; i < choices.length; i++) {
            let element = document.getElementById('answer' + i);
            element.innerHTML = choices[i];
    
            element.addEventListener('click', handleAnswerClick)
          }
    
          showProgress();
        }
      }
    
      function handleAnswerClick (e) {
        let el = e.currentTarget;
        let answer = el.innerHTML;
        el.removeEventListener('click', handleAnswerClick);
        guess(answer);
      }
    
      function showProgress () {
        let questionIndexElement = document.getElementById('question-index');
        let index = questionIndex + 1;
        questionIndexElement.innerHTML = index.toString();
      }
    
      function guess(answer) {
        clearTimeout(timer);
        let answersContainer = document.getElementById('answers-container');
        let answerButtons = answersContainer.querySelectorAll('.default-button');
    
        answerButtons.forEach(function(element) {
          element.disabled = true;
          if (element.innerHTML === questions[questionIndex].correct) {
            element.classList.add('correct');
          }
        });
    
        stopProgressbar();
    
        if (questions[questionIndex].correct === answer) { // correct answer
          score++;
          setQuizText('¡¡Excelente 🤗!!')
        } else if (answer) { // incorrect answer
          setQuizText('Sigue intentando 🤣');
          answerButtons.forEach(function(element) {
            if (element.innerHTML === answer) {
              element.classList.add('wrong');
            }
          });
        } else {
          setQuizText('Piensa más rápido 😛')
        }
    
        questionIndex++;
    
        window.setTimeout(function() {
          populate();
        }, 3000);
      }
    
      function setQuizText (text) {
        let el = document.getElementById('quiz-text');
        el.innerHTML = text;
      }
    
      function showScores () {
        let scoreElement = document.getElementById('score');
        let scoreTotalElement = document.getElementById('score-total');
        let scoreNameElement = document.getElementById('score-name');
    
        scoreElement.innerHTML = score.toString();
        scoreTotalElement.innerHTML = questionLength.toString();
    
        if (score < 4) {
          scoreNameElement.innerHTML = 'Novato'
        } else if (score < 7) {
          scoreNameElement.innerHTML = 'Excelente, pero no tanto'
        } else if (score < 10) {
          scoreNameElement.innerHTML = 'Impresionante'
        } else {
          scoreNameElement.innerHTML = 'Experto de las palabras'
        }  
    
        quizScreen.classList.add('hidden');
        resultScreen.classList.remove('hidden');
      }
    
      function startProgressbar() {
        // We select the div that we want to turn into a progressbar
        let progressbar = document.getElementById('progress-bar');
        progressbar.innerHTML = '';
        // We create the div that changes width to show progress
        let progressbarInner = document.createElement('span');
    
        // Append the progressbar to the main progressbardiv
        progressbar.appendChild(progressbarInner);
    
        // When everything is set up we start the animation
        progressbarInner.style.animationPlayState = 'running';
      }
    
      function stopProgressbar () {
        let progressbar = document.getElementById('progress-bar');
        let progressbarInner = progressbar.querySelector('span');
        progressbarInner.style.animationPlayState = 'paused';
      }
    
    
    
      // your page initialization code here
      // the DOM will be available here
    
    })();
    
    
    </script>
    {% endblock %}

templates/index/base.html
{% load static %}

<!DOCTYPE html>
<html lang="es">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Trivia</title>
  <link rel="shorcut icon" type="image/jpg" href="https://www.listchallenges.com/f/items2020/e414894a-a949-41d6-9977-46603c68336f.jpg">
  <link rel="stylesheet" type="text/css" href="{% static 'css/styles.css' %}">
  
</head>
<body>
  <audio id="soundgame"  loop>
    <source src="{% static 'source/space-level.mp3' %}" type="audio/mp3">
    Tu navegador no soporta audio HTML5.
</audio>
<script>
    // Obtén una referencia al elemento de audio
    var audio = document.getElementById("soundgame");

    // Función para reproducir el audio al hacer clic en algún lugar de la página
    function playAudio() {
        audio.play();
        // Elimina el manejador de eventos después de la primera reproducción
        document.removeEventListener("click", playAudio);
    }

    // Agrega un manejador de eventos para reproducir el audio al hacer clic en cualquier lugar de la página
    document.addEventListener("click", playAudio);
</script>
  {% block content %}{% endblock content %}
  
  
</body>
</html>